# devtools::install_github('jasongbragg/RRtools')
# https://github.com/eilishmcmaster/ReCER_base_analysis_pipeline


library(patchwork)
library(gridExtra)
library(RColorBrewer)
library(circlize) 
# library(scatterpie)
library(tanggle)
library(RSplitsTree)
# library(ggmap)
# library(lubridate)
library(ggplot2)
library(dplyr)
library(data.table)
library(ggrepel)
library(tidyverse)
library(ggsn)
library(ggspatial)
library(readxl)
# library(heatmaply)
library(circlize)
library(ComplexHeatmap)
library(igraph)
library(SNPRelate)
library(geosphere)
library(reshape2)
library(vegan)
# library(ggforce)
library(openxlsx)
# library(stringr)
# library(pracma)
library(ggpubr)
library(RRtools)
library(ggthemes)
library(RColorBrewer)
library(ozmaps)
library(adegenet)
library(tidyr)
library(diveRsity)
library(RRtools)
# library(LEA)
devtools::source_url("https://github.com/eilishmcmaster/SoS_functions/blob/main/sos_functions.R?raw=TRUE")

theme_set(theme_few())

#test 2
# test

setwd("~/Desktop/PhD Analyses/Report-DOre22-7415/Chapter_1/OE")

species <- "OE"
dataset <- "DOre22-7415"
RandRbase <- ""

topskip   <- 6
nmetavar  <- 18


locus_miss <- 0.3 # maximum NA loci 

# "Report_DOre22-7415_SNP_2.csv"

###note that this loads scripts generated by SY to automate / make RnR summary reports from DArTseq data. Should probably be put onto Git#####
# load("PSFsaved_scripts4autom2.RData")

#### Import and QC ####

#Load data and quality filter loci and samples
d1        <- new.read.dart.xls.onerow(RandRbase,species,dataset,topskip, euchits=FALSE, altcount=TRUE)
# qc1       <- report.dart.qc.stats(d1, RandRbase, species, dataset, threshold_missing_loci = 0.8)

d2        <- remove.poor.quality.snps(d1, min_repro=0.96, max_missing=locus_miss)
# qc2       <- report.dart.qc.stats(d2, RandRbase, species, dataset)

d3        <- sample.one.snp.per.locus.random(d2, seed=214241)
# qc3       <- report.dart.qc.stats(d3, RandRbase, species, dataset)

#Load meta data and attach to dart data
m1        <- read.meta.data.full.analyses.df(d3, RandRbase, species, dataset)

# write.table(data.frame(sample=d3$sample_names[!(d3$sample_names %in% m1$sample_names)]), 
#             paste0(species,"/outputs_",site_col_name,"_",species_col_name,"/tables/samples_in_dart_not_in_meta.tsv"), sep="\t", row.names = FALSE)

dms        <- dart.meta.data.merge(d3, m1)

# # remove samples that are NA for site variable 
# samples_with_site_variable <- dm$sample_names[!is.na(dm$meta$analyses[,site_col_name])]
# dms2 <- remove.by.list(dm, samples_with_site_variable)

species_col_name <- 'region'
site_col_name <- 'site'
clonal_threshold <- 0.4
###########################################  clones ########################################### 
# find and remove clones using SNPrelate kinship 

#calculate kinship by population 
# VERY important that the population groups are true genetic groups and not conglomerates of multiple genetic groups
kin <- individual_kinship_by_pop(dms, RandRbase, species, dataset, dms$meta$analyses[,species_col_name], maf=0.1, mis=locus_miss, as_bigmat=TRUE)

kin[is.na(kin)] <- 0
# Finding the clones
kin3 <- ifelse(kin < clonal_threshold, 0, 1)

# cluster the clones 
network <- graph_from_adjacency_matrix(kin3, mode="undirected", diag=F,weighted=T) #makes the network based on k>0.45 

ceb <- cluster_fast_greedy(network) # makes cluster groupings

# get clones 
clones <-as.data.frame(cbind(genet=ceb$membership, sample=ceb$names)) #get the clones from the network as a df
clones_out <- merge(clones, dms$meta$analyses[,c("sample","lat","long",site_col_name,species_col_name)], by="sample") #add some metadata
clones_out <- clones_out[order(as.numeric(clones_out$genet)),] #order the table by genet 
clones_out$genet <- as.numeric(clones_out$genet)

write.xlsx(clones_out, paste0(species,"/outputs_",site_col_name,"_",species_col_name,"/tables/PLINK_clones.xlsx"), asTable = FALSE, overwrite = TRUE)




# Remove duplicate clones from working data 
#close clones with highest quality data (least missingess)
missingness_gt <- as.data.frame(rowSums(is.na(dms[["gt"]]))/ncol(dms[["gt"]])) #get missingness of all samples
colnames(missingness_gt) <- "missingness"
clone_missing <- merge(clones_out, missingness_gt, by.x="sample", by.y=0) # merge the clone data 
clone_missing <- clone_missing[order(clone_missing$missingness),] #order by missingness low to high 

unique_genets <- distinct(clone_missing, genet, .keep_all=TRUE) #keeps the top result for each genet (lowest missingness)

#make a list removing duplicate clones
non_clones <- dms$sample_names[which(!dms$sample_names %in% clones_out$sample)]
approved_clones <- unique_genets$sample

clones_dereplicated <- c(non_clones, approved_clones) # list of sample to keep

# remove clones from dms 
dms_no_clones <- remove.by.list(dms, clones_dereplicated)

###############

maf_val <- 0.5 
sppop_freq <- as.data.frame(table(dms_no_clones$meta$site))
not_n1_sites <- as.vector(sppop_freq[sppop_freq$Freq<=1,1]) #remove groups where n<=1
not_n1_samples <- dms_no_clones$sample_names[which(!(dms_no_clones$meta$site %in% not_n1_sites))]
fst_dms <- remove.by.list(dms_no_clones, not_n1_samples)


# calculate FST and geodist
gds_file <- dart2gds(fst_dms, RandRbase, species, dataset)
pFst      <- population.pw.Fst(fst_dms, fst_dms$meta$analyses[,site_col_name], RandRbase,species,dataset, maf_val=maf_val, miss_val=locus_miss) #calculates genetic distance 
pS        <- population.pw.spatial.dist(fst_dms, fst_dms$meta$analyses[,site_col_name]) #calculates geographic distance between populations


####plot IBD plot

# Make self comparisons NA
diag(pFst$Fst) <- NA
diag(pS$S) <- NA

#Mantel test 
man <- mantel(xdis = pS$S, ydis = pFst$Fst, permutations = 10000, na.rm = TRUE) #mantel test, finds if matrices are signficantly similar
man

# mantel plot
Fst_sig <- cbind(melt(pS$S), unlist(as.list(pFst$Fst)))
colnames(Fst_sig)[3] <- "Geo_dist"
colnames(Fst_sig)[4] <- "Fst"
Fst_sig$Geo_dist2 <-Fst_sig$Geo_dist/1000 

# adding metadata for sites
Fst_sig2 <- merge(Fst_sig, distinct(filtered_site_summary[,c(site_col_name,species_col_name)]), by.x="Var1", by.y=site_col_name, all.y=FALSE)
Fst_sig2 <- merge(Fst_sig2, distinct(filtered_site_summary[,c(site_col_name,species_col_name)]), by.x="Var2", by.y=site_col_name, all.y=FALSE)
Fst_sig2$same_sp <- ifelse(Fst_sig2[,6]== Fst_sig2[,7], paste("Within", species_col_name), paste("Between", species_col_name))

fst_manning <- ggplot(Fst_sig2, aes(x= Geo_dist2, y=Fst, color=same_sp))+geom_point(size=1, alpha=0.3)+
  labs(x="Distance (km)", y="FST", colour="Comparison")+
  # facet_zoom(x=Geo_dist2<2, zoom.size=1)+
  geom_hline(yintercept = 0.3, color="black", linetype="dotted")+
  
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position="bottom")+
  labs(title = paste("Mantel statistic r is", round(man$statistic, 3), ", P =", round(man$signif, 5)))+ theme(plot.title = element_text(size=10))

fst_manning

ggsave(paste0(species,"/outputs_",site_col_name,"_",species_col_name,"/plots/FST_manning.png"),
       fst_manning, width = 15, height = 10, units = "cm", dpi=600)


# Make heatmaps
# geo dist
geo_d <-pS$S #this is a square matrix
mat <- geo_d/1000 # convert to km 

#FST
mat2 <-pFst$Fst
mat2 <- merge(mat2, filtered_site_summary[,1:2], by.x=0, by.y=site_col_name, all.y=FALSE) #add aggregated df to mat2 (fst)
rownames(mat2) <- mat2$Row.names

mat2$Row.names <- NULL
mat2 <- mat2[match(colnames(mat2)[1:nrow(mat2)],rownames(mat2)),]

order_hm <- Heatmap(mat,
                    cluster_rows = TRUE,
                    cluster_columns = TRUE)
od <- colnames(mat)[column_order(order_hm)]

mat = mat[od, od]
mat2 = mat2[od, c(od,species_col_name)]

# specify fst heatmap colours 
gene_col <-  colorRamp2(c(0,0.5,1), c("#8DD3C7", "white", "#FB8072"))


#specify geo heatmap colours
palette <-  colorRamp2(c(0, max(mat, na.rm=TRUE)), c("white", "#80B1D3"))


row_sp_ann <- rowAnnotation(Species = mat2[,species_col_name],
                            col=list(Species=sp_colours),
                            na_col="white",
                            annotation_legend_param = list(labels_gp=gpar(fontsize=6),#fontface="italic",
                                                           title_gp=gpar(fontsize=8),
                                                           title=species_col_name),
                            annotation_name_gp = gpar(fontsize = 0),
                            annotation_name_side="top")

bottom_sp_ann <- HeatmapAnnotation(Species = mat2[,species_col_name], 
                                   col = list(Species = sp_colours),
                                   annotation_name_gp = gpar(fontsize = 0),
                                   show_legend = FALSE,
                                   annotation_name_side="right",
                                   na_col = "white",
                                   annotation_legend_param = list(labels_gp=gpar(fontsize=6),#fontface="italic",
                                                                  title_gp=gpar(fontsize=8),
                                                                  title=species_col_name))

geo <- Heatmap(mat,rect_gp = gpar(type = "none"),
               width = nrow(mat)*unit(4, "mm"),
               height = nrow(mat)*unit(4, "mm"),
               col=palette,na_col="white",
               bottom_annotation = bottom_sp_ann,
               column_names_gp = gpar(fontsize = 6),
               cluster_rows = FALSE,
               cluster_columns = FALSE,
               name="Distance (km)",
               heatmap_legend_param = list(title_gp = gpar(fontsize = 8),
                                           labels_gp = gpar(fontsize = 6)),
               cell_fun = function(j, i, x, y, w, h, fill) {
                 if(i >= j) {
                   grid.rect(x, y, w, h, gp = gpar(fill = fill, col = fill))
                 }
               }
)

# make fst heatmap
gene <- Heatmap(as.matrix(mat2[,1:nrow(mat2)]), rect_gp = gpar(type = "none"),
                # column_title = paste(species, "FST and geographic distance"),column_title_gp = gpar(fontsize = 20),#, fontface = "bold"
                width = nrow(mat2)*unit(4, "mm"),
                height = nrow(mat2)*unit(4, "mm"),
                right_annotation = row_sp_ann,
                col=gene_col,na_col="grey",
                row_names_gp = gpar(fontsize = 6),
                column_names_gp = gpar(fontsize = 0),
                border_gp = gpar(col = "black", lty = 1),
                name="FST",
                cluster_rows = FALSE,
                cluster_columns = FALSE,
                heatmap_legend_param = list(title_gp = gpar(fontsize = 8),
                                            labels_gp = gpar(fontsize = 6)),
                cell_fun = function(j, i, x, y, w, h, fill) {
                  if(i <= j) {
                    grid.rect(x, y, w, h, gp = gpar(fill = fill, col = fill))
                    grid.text(sprintf("%.2f", mat2[,1:nrow(mat2)][i, j]), x, y, gp = gpar(fontsize = 4))
                  }
                })

# Set the file name and parameters
filename <- paste0(species, "/outputs_",site_col_name,"_",species_col_name,"/plots/FST_heatmap.pdf")
gene_width <- nrow(mat2)*unit(4, "mm")
pdf(filename, width = (((nrow(mat2)*4)/10) +8)*0.394, height = (((nrow(mat2)*4)/10)+5)*0.394)
draw(geo + gene, ht_gap = -gene_width)
dev.off()

